### ISSUE TITLE
Command line options on timing routines don't always work correctly

### ISSUE THREAD

**Issue by bjoo** [JeffersonLab/qphix#106]
Some of the command line options for running the timings do not always work correctly.
For example: I've had cases where compression was enabled, even tho no -compress12 option
was given. I have had cases where all the tests ran even tho only -dslash was given.  I will investigate this in 'devel' branch, in case it is still an issue in the latest 'devel'.

**Comment by bjoo** [comment]
fixed by a1394d3acdb72238108a18a9f594844a7fd93334

**Comment by kostrzewa** [comment]
We also encountered this and fixed it. We'll resolve any conflicts in coming merges.
