### ISSUE TITLE
Make BARRIER_TSLICES at least configure time option

### ISSUE THREAD

**Issue by bjoo** [JeffersonLab/qphix#11]
Allow control of frequency of group barriers at configure time. This could then become an autotuning parameter.

**Comment by martin-ueding** [comment]
There is no occurrence of `QPHIX_BARRIER_TSLICES` in the codebase in the CMake branch. Is this still relevant?

**Comment by bjoo** [comment]
Hi Martin, 
 This is not currently relevant I think, since this was a KNC thing. For KNL it may be useful, but I don’t have such a
lowe latency barrier. 

Best, 
B
> On Jun 21, 2017, at 6:19 AM, Martin Ueding <notifications@github.com> wrote:
> 
> There is no occurrence of QPHIX_BARRIER_TSLICES in the codebase in the CMake branch. Is this still relevant?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--------------------------------------------------------------------------------------
Dr Balint Joo              High Performance Computational Scientist
Jefferson Lab
12000 Jefferson Ave, Suite 3, MS 12B2, Room F217,
Newport News, VA 23606, USA
Tel: +1-757-269-5339,      Fax: +1-757-269-5427
email: bjoo@jlab.org       
-------------------------------------------------------------------------------------
