### ISSUE TITLE
Compiler Internal Error: with icc-16

### ISSUE THREAD

**Issue by bjoo** [JeffersonLab/qphix#16]
ICC-16 suffers from 'internal errors':

Seen in:
icpc (ICC) 16.0.0 20150815
icpc (ICC) 16.0.2 20160204

Not necessarily a bug, but may need code-fix to workaround.

**Comment by ddkalamk** [comment]
I think I know what the problem is here. I think there is some change required in shuffle/permute intrinsic in code-generator. Probably I have it fixed in ks-codegen branch. Will take a look and try to fix it.

Dhiraj

**Comment by bjoo** [comment]
Hi Dhiraj,
 Thanks. In the meantime, I have filed a bug with Intel Premier support.

Best,
 B



On February 29, 2016 12:18:40 PM EST, Dhiraj D Kalamkar <notifications@github.com> wrote:
>I think I know what the problem is here. I think there is some change
>required in shuffle/permute intrinsic in code-generator. Probably I
>have it fixed in ks-codegen branch. Will take a look and try to fix it.
>
>Dhiraj
>
>From: Balint Joo [mailto:notifications@github.com]
>Sent: Monday, February 29, 2016 9:13 PM
>To: JeffersonLab/qphix
>Subject: [qphix] Compiler Internal Error: with icc-16 (#16)
>
>
>ICC-16 suffers from 'internal errors':
>
>Seen in:
>icpc (ICC) 16.0.0 20150815
>icpc (ICC) 16.0.2 20160204
>
>Not necessarily a bug, but may need code-fix to workaround.
>
>—
>Reply to this email directly or view it on
>GitHub<https://github.com/JeffersonLab/qphix/issues/16>.
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/JeffersonLab/qphix/issues/16#issuecomment-190297155

-- 
Balint Joó, Scientific Computing Group, Jefferson Lab
Email: bjoo@jlab.org Tel: +1 757 269 5339
Sent form my mobile phone

**Comment by ddkalamk** [comment]
Ok . I tried with ks-codegen branch. Even there I get internal error so my guess seems wrong. So we will have to follow up with Premier support.

Dhiraj

**Comment by bjoo** [comment]
I heard back about this, the issue seems to be the combination of 

#pragma simd
#pragma omp parallel for

in that order, which occurs in some of the BLAS like code. Workarounds suggested were reversing the order of the pragmas, but perhaps a better approach would be to track these down and replace them with OpenMP 4.0 SIMD and / or SIMD parallel for pragmas

Many thanks to Intel Premier Support and Compiler Engineering for their help with this issue.

**Comment by azrael417** [comment]
Hi Balint,

thanks for digging this out. It should not crash though. However, we should use #pragma tmp parallel for sims instead.

Best
Thorsten

**Comment by azrael417** [comment]
I will take care of the OMP 4 conversion and create a new icc16-hotfix branch one that is done.

**Comment by bjoo** [comment]
Thanks Thorsten!
