### ISSUE TITLE
Enable Travis CI within GitHub

### ISSUE THREAD

**Issue by martin-ueding** [JeffersonLab/qphix#26]
I have now added support for Travis CI on `devel`. This is already enabled on [my fork](https://travis-ci.org/martin-ueding/qphix), so every commit I push will be automatically built and tested.

For this repository it can be activated trivially now. Log into https://travis-ci.org/ with the JeffersonLab organization account. Then flick the switch for the `qphix` repository to enable continuous testing.

Could somebody with admin rights on this repository please take two minutes and enable it?

**Comment by bjoo** [comment]
Hi Martin,
 I think it is excellent to have CI. However, let me check at the lab whether enabling this at the Jefferson Lab organization level is OK as regards policy ( e.g. Slack doesn't actually get access to our repo, the repo pushes to it via webhooks )

Best, 
 B

On March 25, 2017 8:28:11 AM EDT, Martin Ueding <notifications@github.com> wrote:
>I have now added support for Travis CI on `devel`. This is already
>enabled on [my fork](https://travis-ci.org/martin-ueding/qphix), so
>every commit I push will be automatically built and tested.
>
>For this repository it can be activated trivially now. Log into
>https://travis-ci.org/ with the JeffersonLab organization account. Then
>flick the switch for the `qphix` repository to enable continuous
>testing.
>
>Could somebody with admin rights on this repository please take two
>minutes and enable it?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/JeffersonLab/qphix/issues/26

-- 
Balint Joó, Scientific Computing Group, Jefferson Lab
Email: bjoo@jlab.org Tel: +1 757 269 5339
Sent form my mobile phone

**Comment by bjoo** [comment]
Travis CI is working nicely now thanks to @martin-ueding !
I will close this issue now.
