### ISSUE TITLE
blas_c.h is not installed

### ISSUE THREAD

**Issue by martin-ueding** [JeffersonLab/qphix#30]
The file `blas_c.h` does not get installed with `make install`. It seems that it is not really used by any of the other files, though.

Should that file be deleted, then?

**Comment by bjoo** [comment]
> On Apr 20, 2017, at 8:23 AM, Martin Ueding <notifications@github.com> wrote:
> 
> The file blas_c.h does not get installed with make install. It seems that it is not really used by any of the other files, though.
> 
> Should that file be deleted, then?

Quite possibly. I think we use the blas_new.h stuff now…

Best, 
 B
--------------------------------------------------------------------------------------
Dr Balint Joo              High Performance Computational Scientist
Jefferson Lab
12000 Jefferson Ave, Suite 3, MS 12B2, Room F217,
Newport News, VA 23606, USA
Tel: +1-757-269-5339,      Fax: +1-757-269-5427
email: bjoo@jlab.org       
-------------------------------------------------------------------------------------

**Comment by martin-ueding** [comment]
I just tried to delete the `blas.h` and `blas_mic.h`. None of the code in `include/qphix` depends on it. There is code in `testBlas.cc` that tests the old and new BLAS implementation against each other. If we are to get rid of `blas.h`, that test has to be disabled as well. Those tests serve as a nice control for the new BLAS code, so we should keep all the code.
