### ISSUE TITLE
Add AVX2 Support

### ISSUE THREAD

**Issue by bjoo** [JeffersonLab/qphix#4]
The Code Generator can produce AVX2 kernels, we should add these and create a new target

**Comment by bjoo** [comment]
Mario Schrock has added this.

**Comment by bjoo** [comment]
The addition of the AVX2 headers (specifically the 16 bit ones) caused nobase_include_HEADERS to become too long and cause me to have 'too many arguments' type errors on the 'make install' target.
I re-jigged the makefile structure to support this. Now each architecture (avx,avx2,etc) has its own Makefile.am with only the files for that architecture. The scheme is:

<arch>_includedir = $(includedir)/qphix/<arch>

nobase_arch_include_HEADERS = ... list of header files ...

Then the make is recursive so in include/  Makefile has SUBDIRS=qphix
in include/qphix the Makefile has 

SUBDIRS=avx avx2 mic qpx scalar
qphix_includedir = $(includedir)/qphix
qphix_include_HEADERS = ...

This way we can hopefully also easily add SSE (if we ever want).

**Comment by m-schroeck** [comment]
I've applied this scheme to the qphix-tmf branch, too. (After having merged 'devel' into it.)
