### ISSUE TITLE
Extend to N_f = 1 + 1

### ISSUE THREAD

**Issue by martin-ueding** [JeffersonLab/qphix#46]
In order to simulate a strange quark in twisted mass, a non-degenerate doublet is required. The solvers have to be adapted to solve two flavors at once.

**Comment by martin-ueding** [comment]
I have merged the CMake build system into my `two-flavor` branch. The regular tests fail, it does not quite work out. These tests are all our trusty one-flavor tests, so nothing should have changed if the specialization to a single flavor would be correct. So I need to find the errors such that nothing is broken by this addition.

**Comment by bjoo** [comment]
Hi Martin, I guess this was merged in today. If you think this is now done, we can close the issue.
Or did you still have some odd behaviour you are chasing?
