### ISSUE TITLE
Reduce verbosity from Geometry Constructor

### ISSUE THREAD

**Issue by bjoo** [JeffersonLab/qphix#57]
I have been meaning to put this for a while. We should reduce the verbosity from the Geometry Constructor. In an HMC run it just prints too much...

**Comment by martin-ueding** [comment]
Oh, sorry about that. I was just doing tests and thought that this would be helpful. There the constructor is only called once. The various test programs had their own output of all that stuff, so I thought that I would unify it.

How about we add a `bool print_arguments = false` to the ctor and then in all the QPhiX test cases one can set this to `true`? Or perhaps it would be easier the other way around?

**Comment by martin-ueding** [comment]
That has been fixed now. The Geometry constructor will not output the verbose information unless you tell it to. All of QPhiX's tests do that, but when you do HMC there should not be any output from Geometry.
