### ISSUE TITLE
memory leak: abstract base classes need destructors

### ISSUE THREAD

**Issue by kostrzewa** [JeffersonLab/qphix#66]
When using the abstract base classes, QPhiX::EvenOddLinearOperator and QPhiX::AbstractSolver, the lack of virtual destructors leads to severe memory leaks.

**Comment by kostrzewa** [comment]
In tmLQCD, we use pointers to the abstract classes to hold pointers to the derived classes.

**Comment by martin-ueding** [comment]
Yes, a virtual destructor is a must for a base class, I should have thought of that. The 1+1 stuff looks promising, I will take of this next, then.

**Comment by martin-ueding** [comment]
Should be fixed now, I have included a virtual dtor with an empty default implementation.
