### ISSUE TITLE
“Refactoring” and “codegen” tags for GitHub Issues

### ISSUE THREAD

**Issue by martin-ueding** [JeffersonLab/qphix#81]
It seems that a lot of issues are about refactoring. They are currently tagged with “enhancement” but I have the feeling that a separate “refactoring” tag would be nice to differentiate a bit more. Perhaps also a “codegen” tag while we are at it?

Could somebody with administrative permissions on this repository please add the two labels?

**Comment by bjoo** [comment]
Created...
