### ISSUE TITLE
Enabling MPI comms for the kernels via configure

### ISSUE THREAD

**Issue by bjoo** [JeffersonLab/qphix#9]
Update the ./configure chain so that the #define for enabling native MPI comms (as opposed to going through QMP) in Dslash can be enabled at configure time, rather than by hand in the .h file

**Comment by martin-ueding** [comment]
If this is still relevant, it should become a CMake option now.

**Comment by bjoo** [comment]
Probably we should do this. It has been on the todo to make it an autoconf option, and
I think it is currently enabled for the nearest neighbors comms part at least.

> On Jun 20, 2017, at 1:29 PM, Martin Ueding <notifications@github.com> wrote:
> 
> If this is still relevant, it should become a CMake option now.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--------------------------------------------------------------------------------------
Dr Balint Joo              High Performance Computational Scientist
Jefferson Lab
12000 Jefferson Ave, Suite 3, MS 12B2, Room F217,
Newport News, VA 23606, USA
Tel: +1-757-269-5339,      Fax: +1-757-269-5427
email: bjoo@jlab.org       
-------------------------------------------------------------------------------------

**Comment by martin-ueding** [comment]
What is the option that you want to expose, `QPHIX_MPI_COMMS_CALLS`?

**Comment by bjoo** [comment]
Sure. That sounds OK. 
 Best, 
 B
> On Jun 21, 2017, at 6:18 AM, Martin Ueding <notifications@github.com> wrote:
> 
> What is the option that you want to expose, QPHIX_MPI_COMMS_CALLS?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--------------------------------------------------------------------------------------
Dr Balint Joo              High Performance Computational Scientist
Jefferson Lab
12000 Jefferson Ave, Suite 3, MS 12B2, Room F217,
Newport News, VA 23606, USA
Tel: +1-757-269-5339,      Fax: +1-757-269-5427
email: bjoo@jlab.org       
-------------------------------------------------------------------------------------

**Comment by martin-ueding** [comment]
I have added that in 26cd35a. Perhaps the help text is not really the perfect description.
