### ISSUE TITLE
Reduce coupling of RandomGauge class

### ISSUE THREAD

**Issue by bjoo** [JeffersonLab/qphix#93]
I like RandomGauge.h but it has many dependencies (unittest.h for assertion() and so forth). Would it be worth refactoring so that we can just include it as a standalone? (It needs also print-utils.h etc?) We can also immediately close this thread if this is a silly comment/issue.

**Comment by martin-ueding** [comment]
The `RandomGauge` indeed is a rather large class as it contains multiple data structures for gauge field and clover term in both QDP++ and QPhiX layouts. We can work on reducing the dependencies to make it easier to use.

We can keep it as an issue here, but I will probably not work on it before mid of October.

**Comment by bjoo** [comment]
No worries Martin. Thanks, B

On July 11, 2017 4:45:25 PM GMT+02:00, Martin Ueding <notifications@github.com> wrote:
>The `RandomGauge` indeed is a rather large class as it contains
>multiple data structures for gauge field and clover term in both QDP++
>and QPhiX layouts. We can work on reducing the dependencies to make it
>easier to use.
>
>We can keep it as an issue here, but I will probably not work on it
>before mid of October.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_JeffersonLab_qphix_issues_93-23issuecomment-2D314467621&d=DwICaQ&c=lz9TcOasaINaaC3U7FbMev2lsutwpI4--09aP8Lu18s&r=SC-qvz5njMoFH6cliT5XZQ&m=_4i0nInyRvg6uLemEvkG4Ghy2_E15pcZFl6mjZ3EXIg&s=_Q6GqpEknUxglMZPQwJUkLuZamw64oyQnzkZ6qhYWvU&e=
>

-- 
Balint Joó, Scientific Computing Group, Jefferson Lab
Email: bjoo@jlab.org Tel: +1 757 269 5339
Sent form my mobile phone

**Comment by martin-ueding** [comment]
I have remove the `masterPrintf` and I am working on moving the `expect_near` into a separate unit test. That however leads to various complications around ODR, template specializations and non-constexpr constructable types. It will take a while …

**Comment by martin-ueding** [comment]
This issue is done, review is outstanding in #94.
